import = [
  # uncomment the flavour you want below:
#"~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
   "~/.config/alacritty/catppuccin-mocha.toml"
]
[window]
opacity = 0.8
blur = true
option_as_alt = "Both"
[font.normal]
family = "Iosevka Nerd Font"
[env]
TERM = "xterm-256color"
